# Generated by Django 3.2.8 on 2022-01-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rel', '0002_alter_address_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CCity',
        ),
        migrations.RenameModel(
            old_name='Interest',
            new_name='IInterest',
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='PPerson',
        ),
    ]
